#!/usr/bin/env python3
"""PART 3 · The NeMo AutoModel recipe (real YAML + launch)  [INTERMEDIATE]

NVIDIA's NeMo AutoModel is the enterprise fine-tuning path on a DGX: it reads a
YAML recipe and runs LoRA/QLoRA/SFT on Hugging Face models with TE-optimized
kernels. This demo writes a REAL recipe into .sandbox/ for our HVAC dataset and
prints the exact container command from the playbook.

Run:  python demos/step03_nemo_recipe.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import config  # noqa: E402
import ftview  # noqa: E402

RECIPE = """\
# NeMo AutoModel — QLoRA recipe for smart-hotel HVAC domain adaptation
# (generated by week19/dgx_finetune/demos/step03_nemo_recipe.py)
model:
  pretrained_model_name_or_path: {base_model}
  load_in_4bit: true                 # QLoRA: 4-bit frozen base

peft:
  peft_scheme: lora
  lora_target_modules: [q_proj, k_proj, v_proj, o_proj]
  dim: 16                             # adapter rank
  alpha: 32

data:
  train_path: /workspace/data/train.jsonl
  val_path:   /workspace/data/val.jsonl
  chat_template: true                # records are OpenAI chat messages

packed_sequence:
  packed_sequence_size: 1024         # pack short examples → better GPU use

step_scheduler:
  local_batch_size: 1
  global_batch_size: 8
  max_steps: 60
  lr: 2.0e-4
  lr_warmup_steps: 6

checkpoint:
  save_dir: /workspace/checkpoints
  save_every_n_steps: 20
"""

LAUNCH = """\
# DGX Spark — launch the QLoRA fine-tune with NVIDIA's NeMo AutoModel container
export HF_TOKEN=...
docker run --gpus all --ipc host --ulimit memlock=-1 \\
  -v "$PWD/.sandbox:/workspace/data" \\
  -v "$PWD/.sandbox/checkpoints:/workspace/checkpoints" \\
  -e HF_TOKEN="$HF_TOKEN" \\
  nvcr.io/nvidia/nemo-automodel:26.02 \\
  python3 /opt/Automodel/examples/llm_finetune/finetune.py \\
    -c /workspace/data/hvac_qlora.yaml
"""


def main() -> None:
    ftview.banner("PART 3", "The NeMo AutoModel recipe", "INTERMEDIATE")
    ftview.mode_line()

    sb = config.ensure_sandbox()
    recipe = RECIPE.format(base_model=config.BASE_MODEL)
    (sb / "hvac_qlora.yaml").write_text(recipe)

    if not (sb / "train.jsonl").exists():
        print("⚠  no dataset yet — run step01_dataset_prep.py first to create train.jsonl.\n")

    print(f"Base model : {config.BASE_MODEL}")
    print(f"Domain     : {config.DOMAIN}")
    print("Wrote real recipe → .sandbox/hvac_qlora.yaml\n")
    print(recipe)
    print("Launch it on a DGX Spark:\n")
    print(LAUNCH)

    print("What each knob does:")
    print("  • load_in_4bit + peft_scheme: lora  → that's QLoRA (fits a 70B on one Spark).")
    print("  • dim/alpha                  → adapter capacity (16/32 is a solid default).")
    print("  • packed_sequence            → stuff short examples together = more tok/s.")
    print("  • max_steps/lr/warmup        → tiny dataset → few steps or you'll overfit.")

    print("\nTakeaway: the recipe IS the experiment — version it in git. Next: the")
    print("Unsloth fast path, then we watch a (simulated) training run.")


if __name__ == "__main__":
    main()
